name: HTML Validation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install HTML5 Validator
        run: pip install html5validator

      - name: Run HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          format: json
          log_level: WARNING
          css: true
          blacklist: invalid

